### ISSUE TITLE
Update axes with new formal parameters

### ISSUE THREAD

**Issue by jsonbecker** [hrbrmstr/vegalite#14]
I'm working on getting some of the text settings that are now available in vegalite by adding them to the `axes.R` file based on this documentation: [](https://vega.github.io/vega-lite/docs/axis.html) and plan to submit a PR.

However, I noticed that the axes.R file is very repetitive, since all axes get the same arguments and differ only on `chnl`.

Would @hrbrmstr be opposed to me refactoring the code so that there is a single `axes` function (could be internal or external) and that `axes_*` just calls that function with the `chnl` argument set? I would keep the documentation as is in all likelihood but it would make sure that adding new formal arguments from vegalite requires a lot less copy and paste work.

**Comment by hrbrmstr** [comment]
you are *awesome*. let me add you as a full on collab/contributor. thank you so much for this.
