### ISSUE TITLE
feature request: static_page function that creates html page from vl spec

### ISSUE THREAD

**Issue by keesterbrugge** [hrbrmstr/vegalite#36]
Hi, 

thanks for your library! I'd like to create dashboards with it that I host as static pages on s3. I was looking for a function that creates such a html file, but I couldn't find it.

The function `embed_spec` is described as follows: 
> Create minimal necessary HTML/JavaScript/CSS code to embed a Vega-Lite spec into a web page. This assumes you have the necessary boilerplate javascript & HTML page shell defined as you see in the Vega-Lite core example.

What about a function that doesn't create the scaffolding necessary to embed the spec, but creates a full static page? A static page that you can then share or upload to s3. Like the following function `static_page`

``` r
library(vegalite)

dat <- jsonlite::fromJSON('[
    {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
    {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
    {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
  ]')

static_page <- function(vl_spec, file_path){
  output_string <-  paste(
    "<!DOCTYPE html>
    <html>
    <head>
    <title>Embedding Vega-Lite</title>
    <script src=\"https://cdn.jsdelivr.net/npm/vega@3\"></script>
      <script src=\"https://cdn.jsdelivr.net/npm/vega-lite@2\"></script>
        <script src=\"https://cdn.jsdelivr.net/npm/vega-embed@3\"></script>
          </head>
          <body>
          <div id=\"vis\"></div>
            
            <script type=\"text/javascript\">
              var yourVlSpec = ", 
    vl_spec, 
    ";
    vegaEmbed('#vis', yourVlSpec);
    </script>
      </body>
      </html>",
    sep = "") 
  
  write(output_string, file_path)
 }
       
vegalite() %>%
  add_data(dat) %>%
  encode_x("a", "ordinal") %>%
  encode_y("b", "quantitative") %>%
  mark_bar() %>% 
  to_spec() %>% 
  static_page(file_path =  "/tmp/vl.html")

```
I've taken the embedding code from https://vega.github.io/vega-lite/usage/embed.html#start-using-vega-lite-with-vega-embed

I think this would be a nice addition to the library. It definitely suits my use case. 

Cheers

**Comment by jsonbecker** [comment]
Why not use an .Rmd and `knitr` to produce the HTML?

**Comment by keesterbrugge** [comment]
I thought `knitr` would turn the plots into static images. I just tried your method and can confirm that the visualizations remain interactive. Thanks!
