### ISSUE TITLE
widget "rendering" in PDF

### ISSUE THREAD

**Issue by hrbrmstr** [hrbrmstr/vegalite#5]
via <https://twitter.com/timelyportfolio/status/704527440853536772>

i have an idea for this but it will require phantomjs being available.

Widgets require a working DOM & javascript environment. I haven't tried rendering any widgets to PDF but I can't imagine any of them working. But, we can send the widget to phantomjs, let it render there and then pull in the resulting bitmap.

I copied https://github.com/hrbrmstr/streamgraph/blob/master/R/phantom.R from another widget github issue discussion but can rejigger it to return markdown like `![](img.png)` or proper HTML (or whatever wld be necessary for knitr).

thoughts, @timelyportfolio?

**Comment by hrbrmstr** [comment]
```
---
title: "pdftest"
author: "Bob Rudis (@hrbrmstr)"
date: "March 1, 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(vegalite)

dat <- jsonlite::fromJSON('[
   {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
   {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
   {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
 ]')

vegalite() %>%
  add_data(dat) %>%
  encode_x("a", "ordinal") %>%
  encode_y("b", "quantitative") %>%
  mark_bar() %>% 
  widgetThumbnail("widget.png")
```

![](widget.png)
```

seems to work with the mod i just made. again, phantomjs is required.

if this is an ok path, i'll need to level up the phantom code a bit to support higher res output (or rendering to PDF for inclusion in PDF).

**Comment by timelyportfolio** [comment]
@hrbrmstr, I would suggest we combine efforts with RStudio on [`webshot`](https://github.com/wch/webshot) which has recently seen some renewed activity.
