### ISSUE TITLE
background not exported?

### ISSUE THREAD

**Issue by masalmon** [hrbrmstr/vegalite#6]
If I do this

```r
dat <- jsonlite::fromJSON('[
    {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
                          {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
                          {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
                          ]')

vegalite(background="red", export=TRUE, renderer="canvas") %>%
    add_data(dat) %>%
    encode_x("a", "ordinal") %>%
    encode_y("b", "quantitative") %>%
    mark_bar()
```

and then export the image by clicking, the resulting PNG still has a transparent background, although the background was red in RStudio. Is this intended?

**Comment by masalmon** [comment]
(this is a very ugly minimal reproducible example :-))

**Comment by hrbrmstr** [comment]
Nope :-) But, it's a Vega-Lite js lib bug, not a vegalite pkg bug (at least from my tests). And, any reproducible example is an awesome reproducible example :-)

**Comment by masalmon** [comment]
Ok, thanks for reporting it.

Yesterday I asked them if they could add the "yearmonthdayhoursminutesseconds" time unit and it's already possible -- including with your package, I was very happy that it was so fast.

**Comment by domoritz** [comment]
We will release a new version with the fix soon.
