### ISSUE TITLE
Problem passing ts to latest version of vegalite

### ISSUE THREAD

**Issue by stephlocke** [hrbrmstr/vegalite#8]
Made a chart gallery, using Rmd and building with travis. My local vegalite version when used would render the charts fine (as would travis previously) but today with the latest `install_github` the charts are blank.

Page source indicates its generated some vega JS according to the source but it's whitespacing.

Code: https://github.com/stephlocke/chartgallery
Output: http://stephlocke.github.io/chartgallery/

------

Digging deeper I found that when I use a standalone example I get some interesting red text 

```
if(!require(vegalite)) devtools::install_github("hrbrmstr/vegalite")
library(vegalite)
vegalite() %>%
  add_data(Seatbelts) %>%
  encode_x("PetrolPrice","quantitative") %>%
  encode_y("DriversKilled", "quantitative") %>%
  mark_point()

## Error in file.exists(source) : invalid 'file' argument
## In addition: Warning message:
## In if (is_url(source)) { :
##   the condition has length > 1 and only the first element will be used
```

Session info:
```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] vegalite_0.5.1.9000

loaded via a namespace (and not attached):
[1] htmlwidgets_0.6 clipr_0.2.0     magrittr_1.5    htmltools_0.3   tools_3.2.3     jsonlite_0.9.19 digest_0.6.9  
```

**Comment by brudis-r7** [comment]
`Seatbelts` is a `ts` object. I'll take a look at your other examples, tho and try to add `ts` support.

**Comment by stephlocke** [comment]
Good point. 

In the overall piece I use a data.table variant of Seatbelts. When I tried to use the data.table version I rabbit holed and error on even a simple example.  Still not comfy with the issue in that respect as a more complex example doesn't error. https://gist.github.com/stephlocke/566d7d0858ecdb23603e

**Comment by brudis-r7** [comment]
see if `0.6.0.9000` fixes it (and it has `ts` support :-)

**Comment by stephlocke** [comment]
`ts` works nicely! :+1: 

Once I've isolated the other issues better I'll separate tickets for them if required
